### ISSUE TITLE
[LLM NODE] The visual reference variable item does not have such a variable, which prevents the workflow from being saved.

### ISSUE THREAD

**Issue by Kain-90** [fdb02983rhy/dify-pdf-process-plugin#5]
<img width="1119" alt="Image" src="https://github.com/user-attachments/assets/2234d953-52b1-4eaf-83d5-00830e0c4ece" />

```
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: temp
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: package
  value:
    plugin_unique_identifier: langgenius/tongyi:0.0.25@325423749d5e71f8b4681af1b2ed46d7686cb1947e443a86ba5d14ac45ff85a4
- current_identifier: null
  type: package
  value:
    plugin_unique_identifier: kalochin/pdf_process:0.0.4@29c7b0927a11333044049de20657119779a06e0eb003b6c5cffaec07e5204332
kind: app
version: 0.3.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1748240276583'
        sourceType: iteration-start
        targetType: llm
      id: 1748240276583start-source-1748240289412-target
      source: 1748240276583start
      sourceHandle: source
      target: '1748240289412'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInLoop: false
        sourceType: iteration
        targetType: answer
      id: 1748240276583-source-answer-target
      source: '1748240276583'
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: tool
      id: 1748240272244-source-1748240607348-target
      source: '1748240272244'
      sourceHandle: source
      target: '1748240607348'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: tool
        targetType: iteration
      id: 1748240607348-source-1748240276583-target
      source: '1748240607348'
      sourceHandle: source
      target: '1748240276583'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 54
      id: '1748240272244'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#1748240276583.output#}}'
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 105
      id: answer
      position:
        x: 1220.1004440484253
        y: 282
      positionAbsolute:
        x: 1220.1004440484253
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        error_handle_mode: terminated
        height: 178
        is_parallel: false
        iterator_selector:
        - '1748240607348'
        - files
        output_selector:
        - '1748240289412'
        - text
        output_type: array[string]
        parallel_nums: 10
        selected: false
        start_node_id: 1748240276583start
        title: Iteration
        type: iteration
        width: 388
      height: 178
      id: '1748240276583'
      position:
        x: 741.8604969550229
        y: 282
      positionAbsolute:
        x: 741.8604969550229
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 388
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        selected: false
        title: ''
        type: iteration-start
      draggable: false
      height: 48
      id: 1748240276583start
      parentId: '1748240276583'
      position:
        x: 24
        y: 68
      positionAbsolute:
        x: 765.8604969550229
        y: 350
      selectable: false
      sourcePosition: right
      targetPosition: left
      type: custom-iteration-start
      width: 44
      zIndex: 1002
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        isInIteration: true
        isInLoop: false
        iteration_id: '1748240276583'
        model:
          completion_params: {}
          mode: chat
          name: qwen2.5-vl-72b-instruct
          provider: langgenius/tongyi/tongyi
        prompt_template:
        - id: 45af34cc-12b5-4cf4-9e6c-c1f3b2d4e3b7
          role: system
          text: '1'
        selected: true
        title: LLM 2
        type: llm
        variables: []
        vision:
          configs:
            detail: high
            variable_selector:
            - '1748240276583'
            - item
          enabled: true
      height: 90
      id: '1748240289412'
      parentId: '1748240276583'
      position:
        x: 128
        y: 68
      positionAbsolute:
        x: 869.8604969550229
        y: 350
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        desc: ''
        is_team_authorization: true
        output_schema: null
        paramSchemas:
        - auto_generate: null
          default: null
          form: llm
          human_description:
            en_US: PDF file to convert to PNG images
            ja_JP: PDF file to convert to PNG images
            pt_BR: PDF file to convert to PNG images
            zh_Hans: 要转换为PNG图片的PDF文件
          label:
            en_US: PDF Content
            ja_JP: PDF Content
            pt_BR: PDF Content
            zh_Hans: PDF 内容
          llm_description: PDF file content to be converted to PNG images
          max: null
          min: null
          name: pdf_content
          options: []
          placeholder: null
          precision: null
          required: true
          scope: null
          template: null
          type: file
        - auto_generate: null
          default: 2
          form: llm
          human_description:
            en_US: Zoom factor for image quality (default is 2)
            ja_JP: Zoom factor for image quality (default is 2)
            pt_BR: Zoom factor for image quality (default is 2)
            zh_Hans: 图像质量的缩放因子（默认为2）
          label:
            en_US: Zoom Factor
            ja_JP: Zoom Factor
            pt_BR: Zoom Factor
            zh_Hans: 缩放因子
          llm_description: Zoom factor to control the quality of output PNG images
          max: null
          min: null
          name: zoom
          options: []
          placeholder: null
          precision: null
          required: false
          scope: null
          template: null
          type: number
        params:
          pdf_content: ''
          zoom: ''
        provider_id: kalochin/pdf_process/pdf_process
        provider_name: kalochin/pdf_process/pdf_process
        provider_type: builtin
        selected: false
        title: PDF to PNG Converter
        tool_configurations: {}
        tool_description: A tool for converting PDF files to PNG images
        tool_label: PDF to PNG Converter
        tool_name: pdf_to_png
        tool_parameters:
          pdf_content:
            type: variable
            value:
            - sys
            - files
        type: tool
      height: 54
      id: '1748240607348'
      position:
        x: 380
        y: 282
      positionAbsolute:
        x: 380
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -176.04139035333424
      y: 55.36356895610942
      zoom: 0.78541537523357
```
